I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 461, in script
    $ music_game_choice_nuria_nuria_nuria += renpy.random.randint(1,10)
  File "game/script.rpy", line 461, in <module>
    $ music_game_choice_nuria_nuria_nuria += renpy.random.randint(1,10)
NameError: name 'music_game_choice_nuria_nuria_nuria' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 461, in script
    $ music_game_choice_nuria_nuria_nuria += renpy.random.randint(1,10)
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 461, in <module>
    $ music_game_choice_nuria_nuria_nuria += renpy.random.randint(1,10)
NameError: name 'music_game_choice_nuria_nuria_nuria' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
A mess 1.0
Thu Mar 31 16:07:04 2022
